### ISSUE TITLE
 JavaScript heap out of memory error when running 'yarn build'

### ISSUE THREAD

**Issue by jaytoday** [austintgriffith/scaffold-eth#114]
To resolve this issue, make sure to be using `node `12.0.0` or newer.

**Comment by codenamejason** [comment]
This also happens when deploying to Fleek and Heroku

**Comment by pabloruiz55** [comment]
> This also happens when deploying to Fleek and Heroku

Even when targeting node 12+?

**Comment by abeauvois** [comment]
what about adding more resources in .gitpod.yml as a temporary fix, then investigate?
