### ISSUE TITLE
Create an ERC1155 token example as an extension of the "simple-nft-branch" for 🏗 scaffold-eth 

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/scaffold-eth#124]
Instead of using ERC721 for "simple-nft-branch", replace it with ERC1155.

Start by reading through and building out the "simple-nft-example" locally:

https://github.com/austintgriffith/scaffold-eth/tree/simple-nft-example

Notice how the readme is kind of like a tutorial that walks your through the setup. 

Try to make this for ERC1155 too.

**Comment by pabloruiz55** [comment]
@austintgriffith we now have the project I did https://github.com/austintgriffith/scaffold-eth/tree/dont-clone-meme
but if you prefer to have an exact copy of `simple-nft-branch` but with erc1155 instead of erc721 I can do it. Let me know!

**Comment by pabloruiz55** [comment]
Done here: https://github.com/austintgriffith/scaffold-eth/tree/simple-erc1155-nft-example
