### ISSUE TITLE
Unhandled Rejection (Error): missing response

### ISSUE THREAD

**Issue by daniel234x** [austintgriffith/scaffold-eth#129]
Please how can I solve this error, I keep getting after I run `Yarn start` 

`Unhandled Rejection (Error): missing response (requestBody="{\"method\":\"eth_accounts\",\"params\":[],\"id\":45,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={}, url="http://localhost:8545", code=SERVER_ERROR, version=web/5.0.9)`

What should I do ?

**Comment by ccarnino** [comment]
I was experiencing this error too. The issue was that the correct order is to `yarn chain` before `yarn start`. So when the frontend starts if finds the node already running.

**Comment by hustqmk** [comment]
I find out that open 127.0.0.1:3000 in my vitual box is ok, but will meet the same error on my host machine
