### ISSUE TITLE
useGasPrice hook will require an API key from 1st July

### ISSUE THREAD

**Issue by TomAFrench** [austintgriffith/scaffold-eth#13]
The `useGasPrice` hook uses the EthGasStation.io API which will [require an API key from next month](https://ethgasstation.info/blog/eth-gas-station-api-will-require-an-api-key-starting-july-1st-2020/).

It appears that this is a hard requirement so this hook will no longer correctly report gas prices from then on.

**Comment by azf20** [comment]
Interestingly https://ethgasstation.info/json/ethgasAPI.json still seems to work
