### ISSUE TITLE
Frontend can’t connect to localhost using Metamask

### ISSUE THREAD

**Issue by kenokenobingo** [austintgriffith/scaffold-eth#147]
After successfulling and deploying `scaffold-eth` from the master branch, I get the following error on the frontend when connecting Metamask to localhost:

```
TypeError: can't access property "name", Object(...)(...) is undefined
```
![Bildschirmfoto 2021-03-26 um 11 36 29](https://user-images.githubusercontent.com/9639767/112619346-83246000-8e27-11eb-91ee-2d4ecc609aa4.png)

**Comment by dhruvinparikh** [comment]
In the `packages/hardhat/hardhat.config.js` add following code

```
networks: {
  hardhat: {
    chainId: 1337
  },
}
```

Also voice the issue in MetaMask [here](https://github.com/MetaMask/metamask-extension/issues/9827)

**Comment by kenokenobingo** [comment]
Thanks, but it’s still not working.

**Comment by kenokenobingo** [comment]
My bad, used a wrong account on Metamask. 🙄

**Comment by johnnieskywalker** [comment]
How can I specify on which port is local blockchain running ?
