### ISSUE TITLE
Etherscan verification issue

### ISSUE THREAD

**Issue by AbhimanyuG** [austintgriffith/scaffold-eth#155]
I'm trying to deploy to rinkeby network, the smart contract deployment went through fine but it is unable to verify the code on etherscan.

- Configured the API key for etherscan
- Uncommented verify snippet in deploy.js
```
  await run("verify:verify", {
    address: yourContract.address,
    constructorArguments: ['0x123c07d71259eaeb5c3d664c853795a88a452195'] // If your contract has constructor arguments, you can pass them as an array
  })
```

It seems that verify task is unable to get bytecode as shown below, however bytecode exists ([Etherscan](https://rinkeby.etherscan.io/address/0x0036bb901eb727a72248e43726c6279dc2a8cf01#code)):

```
 📄 YourContract deployed to: 0x0036Bb901eb727a72248e43726c6279Dc2A8cF01
 ⛽ 0.000477333 ETH, tx hash 0xef5ca062cae29f68f88ebd36ec07efce8c10567a8038a38ba686a0d1f3fb26db
verifying on etherscan
NomicLabsHardhatPluginError: The address 0x0036Bb901eb727a72248e43726c6279Dc2A8cF01 has no bytecode. Is the contract deployed to this network?
The selected network is rinkeby.
    at Object.retrieveContractBytecode (/Users/agrover/Documents/projects/scaffold-eth/packages/hardhat/node_modules/@nomiclabs/hardhat-etherscan/src/network/prober.ts:103:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/agrover/Documents/projects/scaffold-eth/packages/hardhat/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:198:31)
    at Environment._runTaskDefinition (/Users/agrover/Documents/projects/scaffold-eth/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/agrover/Documents/projects/scaffold-eth/packages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:14)
```

**Comment by AbhimanyuG** [comment]
I also checked API stats for my API key on Etherscan, it shows no call in the last hour - in case this info helps.

**Comment by azf20** [comment]
This might be a syncing issue - what happens if you run again, but don't deploy this time (comment that line out), just run the verify snippet replacing `yourContract.address` with 0x0036Bb901eb727a72248e43726c6279Dc2A8cF01?
If that's it I think we have maybe seen this before @austintgriffith, might need to add a sleep just to give it time to synchronise

**Comment by AbhimanyuG** [comment]
> This might be a syncing issue - what happens if you run again, but don't deploy this time (comment that line out), just run the verify snippet replacing `yourContract.address` with 0x0036Bb901eb727a72248e43726c6279Dc2A8cF01?
> If that's it I think we have maybe seen this before @austintgriffith, might need to add a sleep just to give it time to synchronise

Yes, that is right! I ran deploy.js again this time hardcoding the contract address on verify call, it worked. I'll add a sleep() and check again.

**Comment by pabloruiz55** [comment]
Closing as we don't have moved away from the deploy.js script in favor of Hardhat Deploy. Once contracts are deployed you just need to run the following on the terminal: 
```
cd packages/hardhat
yarn etherscan-verify --network <network_of_choice>
```
