### ISSUE TITLE
Wrong network

### ISSUE THREAD

**Issue by ccarnino** [austintgriffith/scaffold-eth#161]
I launch the node, deploy the contracts and start the react app. I can see the dashboard. So all good.

I open metamask (clean), switch to Localhost, add the private key of the first account generated when launching a node. I see it correctly in metamask.

I Connect to metamask inside the react app. I authorise correctly. I get the confirmation and the page reloads. Then I get the error that I am not connected to the right network.

<img width="1064" alt="Screenshot 2021-04-19 at 16 55 20" src="https://user-images.githubusercontent.com/161903/115266336-089de600-a130-11eb-89cc-9d312c60ff69.png">

I tried on Firefox and Chrome. Same result.

I tried to do as suggested [here](https://github.com/austintgriffith/scaffold-eth/issues/147) but no luck. If I set the chainId to 1337, then when I relaunch the node and try to deploy the contracts I get an error.

What it could be?

**Comment by zy0n** [comment]
maybe also check the network id set in? [packages/src/react-app/constants.js](https://github.com/austintgriffith/scaffold-eth/blob/e834a66d59231f86f28b413595d812bf71056ab9/packages/react-app/src/constants.js#L25)

**Comment by ccarnino** [comment]
I tried to look and update the chainId everywhere in the codebase, but no good results. I made a video showing what I do, in case it helps finding the issue.
https://youtu.be/bLwOEaxZIVA

**Comment by ccarnino** [comment]
The way I solved this, was to setup in Metamask, for the localhost network the chain id `31337` instead of the default `1337`... It took me forever... Is this normal??
<img width="363" alt="Screenshot 2021-04-20 at 21 36 54" src="https://user-images.githubusercontent.com/161903/115460750-8a6d3c80-a220-11eb-86ec-6891394ba34a.png">

**Comment by codenamejason** [comment]
This is because MetaMask mistakenly assumes all networks in http://localhost:8545 to have a chain id of 1337, but Hardhat uses a different number by default. In the meantime, to resolve this you can set the chainId of Hardhat Network to 1337 in your Hardhat config.
``` javascript
networks: {
  hardhat: {
    chainId: 1337
  },
}
```

REF:
https://hardhat.org/metamask-issue.html
