### ISSUE TITLE
nifty-ink-dev local

### ISSUE THREAD

**Issue by monerador** [austintgriffith/scaffold-eth#168]
I tried running nifty-ink-dev branch locally and it doesn't load because it doesn't find a few fields in the graph...

Error! GraphQL error: Type `Ink` has no field `bestPrice` GraphQL error: Type `Ink` has no field `bestPriceSource` GraphQL error: Type `Ink` has no field `bestPriceSetAt` GraphQL error: Type `Ink` has no field `likeCount` GraphQL error: Type `Ink` has no field `likes`

I guess this is something that needs to be added to the mappings?

**Comment by azf20** [comment]
Apologies for the delay - I know what this is, will merge in the latest subgraph when I get a moment!

**Comment by azf20** [comment]
This should now be fixed in this commit https://github.com/austintgriffith/scaffold-eth/commit/488cf5cd9d35bfda7a2e97f4b829e882e847c3b7, but let me know if you still see issues!
