### ISSUE TITLE
enable "template repository" usage, in addition to forking / branching

### ISSUE THREAD

**Issue by artdgn** [austintgriffith/scaffold-eth#169]
First, thanks for the insanely cool project and tutorials!!

## The issue
The recommendation throughout the docs and tutorials is to fork or work in a branch. 

Since this repo seems more like a framework / tool rather than a specific dapp, it seems that the branches / forks model limits some of its usage. First, the name of the repo stays the same (and naming is famously both hard and important). This hides the vastly different dapps each fork / branch is about. Additionally, it puts an implementation detail (what is used under the hood), ahead of the actual purpose of the underlying dapp. It also limits the future evolution of a dapp by coupling it to the framework on the version control level (requiring a new repo if the dapp and the framework drift away far enough).

## Proposal
Allow using the repo as [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template#about-repository-templates) (this also includes some key differences between the mechanisms) that will allow creating new repositories from the template instead of forking. It should be [easy to allow](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) and only add a new way to use this wonderful tool without detracting anything from the current recommended way. This mechanism also ensures highly visible crediting of this repo in each new usage (just as a fork would) - see example below.

## Existing example
Here's an example of a template mechanism. This is the template repo [fastai/faspages](https://github.com/fastai/fastpages) (note the "Use this template" button), and this is a [repo that's using it](https://github.com/artdgn/pages). The attribution is clearly visible under the repo name, but the repo has its own name and history. It's also possible to use the main repo to get latest updates [either manually](https://stackoverflow.com/questions/56577184/github-pull-changes-from-a-template-repository/56577320) or [semi-automatically by github actions](https://github.com/artdgn/pages/pull/5).

What do you think?

**Comment by codenamejason** [comment]
This is what I did in my repo after forking Scaffold-Eth.

**Comment by artdgn** [comment]
> This is what I did in my repo after forking Scaffold-Eth.

@codenamejason Yeah that should work for you, but there are two problems with that for anyone else:
1. It's probably not a good idea for others to use your fork's template because it may become outdated (if you don't keep syncing it), or contain changes they may not want.
2. The attribution goes to your fork instead of the main repo.

Any chance @austintgriffith would be willing to tick that box in the settings?

**Comment by codenamejason** [comment]
@artdgn I wasn't suggesting anyone use mine. They can do the same thing...

**Comment by austintgriffith** [comment]
word this is dope, let's try it:
![image](https://user-images.githubusercontent.com/2653167/117188006-c7e1d600-ad99-11eb-8177-698cac5850f7.png)
 🧑‍🚀.  🚀

**Comment by codenamejason** [comment]
gonna close this now...
