### ISSUE TITLE
New data is not immediately available after tx is confirmed

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#190]
https://github.com/austintgriffith/scaffold-eth/blob/5f26effafc5c68cbdf767139ca44c9acf654b75b/packages/react-app/src/views/ExampleUI.jsx#L45

@austintgriffith I'm testing this on Rinkeby and I get a different behavior than locally. 
The following code is executed and then some contract variables are read again to update the UI.

```
  async function endProject(){
    try{
      const result = tx(freelancerContract.endProject(), update => {
        if (update && (update.status === "confirmed" || update.status === 1)) {
          loadContractData(freelancerContract);
        }
      });
    }catch (e) {
      console.log(e);
    }
  }
```
The code above on a local chain will get me whatever was updated on the contract immediately as soon as the tx status comes back as confirmed/1, which is the ideal behavior.

Whereas on Rinkeby when querying, I still get the old data. 
The following code will get me the updated data by adding some sleep, but feels hacky. (Tried with 2s sleep and it didn't work, 5s seemed to do the trick).

```
async function endProject(){
    try{
      const result = tx(freelancerContract.endProject(), async update => {
        if (update && (update.status === "confirmed" || update.status === 1)) {
          await new Promise(r => setTimeout(r, 5000));
          loadContractData(freelancerContract);
        }
      });
    }catch (e) {
      console.log(e);
    }
  }
```

**Comment by pabloruiz55** [comment]
Actually, the sleep is no good either, only works if tx is actually confirmed before the wait is over.
I've switched over to doing txs without the Transactor helper like so: 

```
  async function startTask(_id){
    const tx = await freelancerContract.startTask(_id);
    showNotification(tx)
    await tx.wait();
    loadContractData(freelancerContract);
  }
```
With the above I do get the updated data after the `await tx.wait();`.
Maybe the Transactor function is missing such thing?

**Comment by azf20** [comment]
Hey! Good catch, I think this functionality varies a bit dependent on the Ethereum client, as you say `.wait()` is required for some - I am actually making some updates to the Transactor at the moment (along with quite a bit more refactoring), so added that in and it is working on a local geth node (which had the same behaviour you describe on Rinkeby).

**Comment by pabloruiz55** [comment]
@azf20 awesome! Looking forward to this update!

**Comment by pabloruiz55** [comment]
@azf20 tested this and unfortunately, while it does fix the issue, it introduces a regression. 
With the .wait() added now the whole thing waits for the receipt which causes things to go unresponsive. 1- The notify.js notification will not pop up anymore saying "transaction in progress" and whatever goes in the promise when you call tx(contractFunction, update =>(){} will only execute once (when transaction is confirmed).

I tried to tinker with this a bit to find a fix but I wasn't able to :(

**Comment by azf20** [comment]
Yep you're right - I tried moving the wait() to just before the result return statement, and that seemed (?) to do what it needs to do? See here: https://github.com/austintgriffith/scaffold-eth/pull/192/commits/76c3c73101bfc84aa568be4d7a15f749f4c398b4
Thanks for looking into this!
