### ISSUE TITLE
Wallet Connect Fails -  Unhandled Rejection (Error): No RPC Url available for chainId: 56

### ISSUE THREAD

**Issue by mickeysox** [austintgriffith/scaffold-eth#195]
Followed full instructions as per branch (Sign In With Web3).  I am able to connect to MetaMask via chrome, however if I scan the QR code on MetaMast via my iPhone, I receive the following error:

Error 1 of 2 

Unhandled Rejection (Error): No RPC Url available for chainId: 56
WalletConnectProvider.updateRpcUrl
src/index.ts:411
WalletConnectProvider.<anonymous>
src/index.ts:386
▶ 3 stack frames were collapsed.
callback
src/index.ts:320
(anonymous function)
src/events.ts:66
EventManager.trigger
src/events.ts:61
WalletConnect._handleSessionResponse
src/index.ts:899
callback
src/index.ts:981
(anonymous function)
src/events.ts:66
EventManager.trigger
src/events.ts:61
WalletConnect.<anonymous>
src/index.ts:959
fulfilled
node_modules/tslib/tslib.es6.js:71
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

2 of 2 

TypeError: Cannot read property 'name' of undefined
App
src/App.jsx:176
  173 | message={"⚠️ Wrong Network"}
  174 | description={
  175 |   <div>
> 176 |     You have <b>{NETWORK(selectedChainId).name}</b> selected and you need to be on{" "}
      | ^  177 |     <b>{NETWORK(localChainId).name}</b>.
  178 |   </div>
  179 | }
View compiled
▶ 17 stack frames were collapsed.
getPrice
src/hooks/ExchangePrice.js:20
  17 |     );
  18 |     const pair = await Fetcher.fetchPairData(DAI, WETH[DAI.chainId], mainnetProvider);
  19 |     const route = new Route([pair], WETH[DAI.chainId]);
> 20 |     setPrice(parseFloat(route.midPrice.toSignificant(6)));
     | ^  21 |   }
  22 | }
  23 | getPrice();
View compiled

**Comment by azf20** [comment]
hi - did you have BSC Mainnet selected in your Metamask mobile?

**Comment by captnseagraves** [comment]
@mickeysox @azf20 is this issue still relevant? Looking to groom the backlog.

**Comment by azf20** [comment]
I think we can close this, @mickeysox please re-open if you are still having issues, thanks!
