### ISSUE TITLE
Simple NFT Example - mint.js script missing

### ISSUE THREAD

**Issue by kristaffa** [austintgriffith/scaffold-eth#204]
[Simple NFT Example](https://github.com/austintgriffith/scaffold-eth/tree/simple-nft-example)

I'm trying to run the example but some of the code mentioned in the readme document is missing.

![image](https://user-images.githubusercontent.com/3483272/122573317-902ba680-d046-11eb-9e78-157b74c0ab11.png)

When the website loads in react I see something different than expected:
![image](https://user-images.githubusercontent.com/3483272/122573462-bbae9100-d046-11eb-8b3d-b64de82e633c.png)

Please advise, I'm not sure of someone checked in the wrong code by mistake.

**Comment by kristaffa** [comment]
not s bug

**Comment by ipatka** [comment]
when you clone the repo you will be on the main branch but you need to be on the simple-nft-example branch

run `git checkout simple-nft-example`

**Comment by pabloruiz55** [comment]
From the looks of it you cloned the repo but didn't checkout the simple-ntf-example branch.
