### ISSUE TITLE
nft-auction branch not workign

### ISSUE THREAD

**Issue by slarkfury** [austintgriffith/scaffold-eth#208]
I was expecting to see this page
![image](https://user-images.githubusercontent.com/31196185/122822059-98d0e680-d2ab-11eb-9ae3-804b559f78ad.png)

but I am just getting this page
![image](https://user-images.githubusercontent.com/85189203/122822219-c9b11b80-d2ab-11eb-9db1-647f4fdff909.png)

Can anyone please tell me if this branch is changed?

**Comment by ipatka** [comment]
what branch are you on? make sure you do `git checkout nft-auction`

**Comment by slarkfury** [comment]
I am in nft-auction branch already

**Comment by slarkfury** [comment]
@ipatka https://github.com/austintgriffith/scaffold-eth/blob/nft-auction/packages/react-app/src/App.jsx#L236
As you can see on this link, the first url is showing just YourContract component, not gallery. Thank you

**Comment by pabloruiz55** [comment]
It seems like @viraj124 lastest commit on this branch overrode a lot of it...
@viraj124 would you mind looking into reverting those changes? 
https://github.com/austintgriffith/scaffold-eth/commit/bea302618a91917395e8624c219624f672a709e1#diff-a7537a962908e0277100acf2a73555c0b82075f18978a904eb34930d9a174d49

**Comment by viraj124** [comment]
@slarkfury @pabloruiz55 thanks for pointing this out let me debug

**Comment by viraj124** [comment]
@slarkfury the branch is working now apologies for the inconvenience
