### ISSUE TITLE
Rarible Starter App - Create sell order - Unhandled Rejection (TypeError): Cannot read property 'domain' of undefined

### ISSUE THREAD

**Issue by kristaffa** [austintgriffith/scaffold-eth#211]
If I try to create a sell order (after successfully approving) I get the following error:

![image](https://user-images.githubusercontent.com/3483272/123111621-f5134200-d434-11eb-8432-04028f7c0a7b.png)

Please advise

**Comment by ipatka** [comment]
Can you share the result of the `console.log(order)` step above?

Also can you share a few more details about the steps you took? Did you deploy a `YourCollectible` contract or are you using the default one.

**Comment by ipatka** [comment]
Oh i think I know what happened. when you set the price, make sure you press the 'star' to convert from ETH to Wei.

For example, if you just enter 0.2, you will get the error you described

Instead, press the start and it will convert 0.2 to 200000000000000000

Then it will succeed.

I'll add some additional messages/ protections to help with that error in the future.

This will fail

![Screen Shot 2021-06-23 at 10 18 50 AM](https://user-images.githubusercontent.com/4401444/123113305-71ddf600-d40c-11eb-96f3-fda1571ee5e2.png)

This will work
![Screen Shot 2021-06-23 at 10 18 55 AM](https://user-images.githubusercontent.com/4401444/123113329-77d3d700-d40c-11eb-8aff-944bfdd7f157.png)

**Comment by kristaffa** [comment]
I'm running it on Rinkeby(since Ropsten is having issues today)  and the didn't realise that I had to update the rarible API reference to https://api-staging.rarible.com/protocol/v0.1/.
