### ISSUE TITLE
Add Netlify-cli deploy command

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#221]
Netlify is widely used, we could provide a command to deploy to Netlify from the terminal as with Surge, S3, etc.
https://cli.netlify.com/

**Comment by codenamejason** [comment]
This would be a great feature but I have not yet been able to CI with Netlify.

**Comment by pabloruiz55** [comment]
No need to add commands since most of the work is done by installing netlify-cli globally.
Instead, I've added step by step instructions to the docs on how to do it.
https://docs.scaffoldeth.io/scaffold-eth/deployment/shipping-your-app
