### ISSUE TITLE
Add support for multiple node providers

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#222]
Right now Infura is hardcoded in some places where you can only change the API key. Ideally, we should do a bit of refactoring so the developer can easily change the node provider in constants.js.

**Comment by Nrestrepo05** [comment]
Hello! I'd like to work on this!

**Comment by pabloruiz55** [comment]
@Nrestrepo05 awesome! Here's an example of what I mean:
https://github.com/austintgriffith/scaffold-eth/blob/1e8e7de390e14fcda6a5ca093c9b9f929351bc7a/packages/react-app/src/App.jsx#L59

Instead of having Infura hardcoded this should come from a constant in constants.js.

**Comment by azf20** [comment]
Could also be worth investigating ethers default provider, though might lose the polling advantage introduced by the Static rpc provider https://docs.ethers.io/v5/api/providers/#providers-getDefaultProvider

**Comment by pabloruiz55** [comment]
> Could also be worth investigating ethers default provider, though might lose the polling advantage introduced by the Static rpc provider https://docs.ethers.io/v5/api/providers/#providers-getDefaultProvider

YES! At the very least we could replace the scaffoldEth provider with the above.
const scaffoldEthProvider = new ethers.providers.StaticJsonRpcProvider("https://rpc.scaffoldeth.io:48544");

So instead of using Austin's rpc node, scaffoldEthProvider becomes ethers default provider.

Then on the next line we keep the static provider with the improvement suggested in this issue to show how to use your own which instead of being only Infura you can switch to something else like Alchemy if you like.

**Comment by peakboyq** [comment]
Who got dat ⛽

**Comment by peakboyq** [comment]
Adding the multi nods

**Comment by peakboyq** [comment]
Am I doing this right

**Comment by peakboyq** [comment]
Enhance!

**Comment by captnseagraves** [comment]
@Nrestrepo05 have you made any progress on this? 

@pabloruiz55 @codenamejason any word or PRs on this?

**Comment by codenamejason** [comment]
@captnseagraves we can close this one, we have updated the rpc endpoints code already.
