### ISSUE TITLE
When using ethers.js wallet, Transactor is unable to properly parse errors

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#224]
How to reproduce:

1. Deploy the default contracts and UI
2. Use the app with a BurnerWallet (which is the case by default, make sure you are not using Metamask).
3. Submit an empty new purpose, which will revert with "purpose can not be empty".
4. Instead of seeing a nice error, the error is caught but it's unable to properly parse it and can't access all the data.

You might, instead, get something like this:
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":60,\"error\":{\"code\":-32603,\"message\":\"VM Exception while processing transaction: revert \\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000@\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0018Purpose can not be empty\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\"}}","error":{"code":-32603},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x1dcd65000\",\"from\":\"0x8760db2223686b352d4993deb77a47982c502992\",\"to\":\"0x5fbdb2315678afecb367f032d93f642f64180aa3\",\"data\":\"0xeb68757f00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":60,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"}, tx={"data":"0xeb68757f00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000","to":{},"from":"0x8760Db2223686B352D4993DEb77A47982C502992","gasPrice":{},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.3.0)
    at Logger.makeError (1.chunk.js:87437)
    at Logger.throwError (1.chunk.js:87447)
    at 1.chunk.js:78554
    at async Promise.all (:3000/index 5)
```

**Comment by azf20** [comment]
hey I think this was fixed in this commit: https://github.com/austintgriffith/scaffold-eth/commit/0cf8280e628645535c1a339011eede29cae401dc#diff-b28b1ed9821f38c64524ea13e19264bb0772f8376afffd5d8a1f8277621833eb

**Comment by pabloruiz55** [comment]
Hey @azf20 not so much. That change makes the notification output read a bit better by not showing the whole error output, but it doesn't show the actual revert message as it should and it does with Metamask. 
See the screenshots below:
With BurnerWallet we get this un-parsed error string, also the notification doesn't specify the revert reason. 😞 😞 😞 😞 
<img width="1204" alt="Screen Shot 2021-06-27 at 10 23 52 AM" src="https://user-images.githubusercontent.com/526558/123546195-fe045c00-d731-11eb-985e-d2bd991e10bb.png">

With Metamask we get this nice object and the rever reason 😃 
<img width="1080" alt="Screen Shot 2021-06-27 at 10 24 52 AM" src="https://user-images.githubusercontent.com/526558/123546243-27bd8300-d732-11eb-9b68-01d9eaeed629.png">
<img width="1027" alt="Screen Shot 2021-06-27 at 10 25 05 AM" src="https://user-images.githubusercontent.com/526558/123546245-28eeb000-d732-11eb-90b5-7934ff1517ba.png">

**Comment by azf20** [comment]
Ah yes right you are. That is a shame. The burner account doesn't actually use BurnerWallet, it is just a vanilla [ethers.js wallet](https://docs.ethers.io/v5/api/signer/#Wallet), but it seems like it's a bit of a challenge between Ethers and the blockchain client per [this issue](https://github.com/ethers-io/ethers.js/issues/871).

And it seems like Metamask also isn't immune given the client dependency, as when I deploy on Rinkeby / Kovan I don't get the nice error on Metamask either.

Rinkeby 
![image](https://user-images.githubusercontent.com/9612972/123547804-15efd600-d75a-11eb-9d8d-a972cced5718.png)

Kovan
![image](https://user-images.githubusercontent.com/9612972/123547964-c78f0700-d75a-11eb-9cac-d99323f250ee.png)

**Comment by pabloruiz55** [comment]
Added a fix here:
Tested with Metamask and with default ethers signer.
https://github.com/austintgriffith/scaffold-eth/pull/237
