### ISSUE TITLE
Gas burn calculator 

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#232]
Austin Griffith, [Jun 29, 2021 at 10:05:57 AM]:
Here is a quick challenge for any 🏗 scaffold-eth builders. Let’s create this gas calculator and deploy it to surge: https://eth.build/build#8173d0c88ea453e7b5f59f47fed9dd04062a8930c3cf23067819165c4f491b40

![photo_2021-06-29 10 24 35](https://user-images.githubusercontent.com/526558/123805169-39cf2b00-d8c4-11eb-99c5-374acf82d223.jpeg)

(You put in how much gas you are going to burn and it looks at gas price and ETH price to give you a quick USD amount)

**Comment by harryranakl** [comment]
good idea, probably can give a try

**Comment by harryranakl** [comment]
<img width="641" alt="Screenshot 2021-06-30 at 4 02 19 PM" src="https://user-images.githubusercontent.com/35558569/123924519-a0d00b00-d9bc-11eb-9779-3e275a1b68b6.png">

**Comment by harryranakl** [comment]
http://eth-gas-burn-calc.surge.sh/

**Comment by pabloruiz55** [comment]
Awesome! Can you please open a PR against this branch? https://github.com/austintgriffith/scaffold-eth/tree/gas-calculator

**Comment by harryranakl** [comment]
https://github.com/austintgriffith/scaffold-eth/pull/239
