### ISSUE TITLE
Error messages are hard to read

### ISSUE THREAD

**Issue by austintgriffith** [austintgriffith/scaffold-eth#236]
Something changed in 🏗 scaffold-eth or HardHat and our errors are really hard to read. 

When you had a require statement fail a month ago, it was clear what was wrong. 

Now you get: 
![image](https://user-images.githubusercontent.com/2653167/124005473-5cca0f80-d996-11eb-9312-8b39ba5a3bb0.png)
(this same info shows up in a quick notification)

Can we parse the "message" and display that in notification so the user can easily see what the problem was?

**Comment by pabloruiz55** [comment]
Please see original discussion here #224 
Just submitted a potential fix here: https://github.com/austintgriffith/scaffold-eth/pull/237
Some additional testing would be appreciated.
