### ISSUE TITLE
Errors with hardhat 2.4.0

### ISSUE THREAD

**Issue by marceljay** [austintgriffith/scaffold-eth#274]
After merging from the current scaffold-eth master into our repository, we could not deploy contracts due to an error:
`ProviderError: TypeError: Cannot read property 'gteHardfork' of undefined`

This was fixed by using hardhat 2.4.3, see here:

https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.3

**Comment by azf20** [comment]
thanks! this was fixed here https://github.com/austintgriffith/scaffold-eth/pull/278 by @ShravanSunder
