### ISSUE TITLE
misguiding error log: Unhandled Rejection Error with tx.wait()

### ISSUE THREAD

**Issue by atlasdevorient** [austintgriffith/scaffold-eth#283]
I got "Unhandled Rejection Error" after hitting mint button, the error points to the ``tx.wait()``  function returned undefined. 
The main reason was the tx reverted because of insufficient fund, thrown in the chain console.

**Comment by captnseagraves** [comment]
@atlasdevorient Can you provide more information about this issue? What branch you are working in, steps to reproduce, etc.

**Comment by atlasdevorient** [comment]
I just wanted to tie the main reason of the interruption and the error message, they seem irrelevant to each other so confuse the devs. That's it. The error is shown by react, on the webpage, but the main reason was among the log lines in the console which yarn chain script runs. The error seems like a JS error, but the reason was about the balance of the wallet.
