### ISSUE TITLE
moonshotcollective.space updates

### ISSUE THREAD

**Issue by owocki** [austintgriffith/scaffold-eth#289]
https://moonshotcollective.space/

remove the duplicate names (auryn/owocki, etc)

Change the copy "For the first time ever, it is possible to program our values into our money. We value coordination, so why not use programmable money to create better coordination tools? The moonshot collective is a collection of builders & web3 community members who are looking to prototype experiments in coordination (whether thats public goods, private goods, governance tools)." to 

"The moonshot collective is a collection of builders & web3 community members who are looking to prototype experiments in coordination (whether thats public goods, private goods, governance tools)."

change the trello link in announcements to https://trello.com/invite/b/qDaciNgF/a5baf02df6aeb4260038a8d616d007bf/moonshot-collective

add a link to github issues in the header that goes to https://github.com/austintgriffith/scaffold-eth/issues/

**Comment by owocki** [comment]
cc @austintgriffith

**Comment by austintgriffith** [comment]
I guess when a branch of scaffold-eth starts to get its own issues it is probably time to fork it to its own repo.
