### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by polal2is** [austintgriffith/scaffold-eth#309]
Hey thanks for that great piece of work ! 

I'm getting the follwing error at yarn start for the "buyer-mints-nft" fork:

`Module not found: Can't resolve './assets.js' in '\buyer-mints-nft\packages\react-app\src'`

Any idea how to go around that ?

Thanks a lot in advance !

**Comment by polal2is** [comment]
I figured it out!
There is an error in the setup tutorial :

`cd simple-nft-example` -> should be `cd buyer-mints-nft`
`yarn upload`
`yarn deploy`

Then the app is waiting for the `yarn upload` otherwise it obviously can't find the assets.js

Fixed

**Comment by codenamejason** [comment]
Closing...
