### ISSUE TITLE
dBoosting NFT Minting Example

### ISSUE THREAD

**Issue by benjaminmbrown** [austintgriffith/scaffold-eth#381]
dBoosting (Derivative Boosting) is when a new mint project increases the value of one or more baseline NFT projects by creating #dNFT (derivative NFT) that requires features of the baseline NFT(s) .

See: Lootproject

I think it would be valuable for the community to see how one can take two separate projects and create a derivative that increases the value of all.

Example:

If user has a SuSquares NFT, they are allowed to mint the new #dNFT.

The new #dNFT might be a loot drop or character w/ properties.

The #dNFT has a name change feature.

In order to change the #dNFT name, you must use Name Change Token ($nct) which is currently a part of the Hashmasks project.

In this situation, both SuSquares and Hashmasks holders benefit from the new derivative because their utility / use cases have expanded. The #dNFT leverages existing components

My thread on the topic: https://twitter.com/benjaminmbrown/status/1434541827185651715?s=20

**Comment by benjaminmbrown** [comment]
I was unable to add this to pipeline board @austintgriffith

**Comment by codenamejason** [comment]
I added @benjaminmbrown  to the pipeline
