### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Jharmony** [austintgriffith/scaffold-eth#383]
After pulling the Github repo, then trying to follow step-by-step configuration instructions,  I keep receiving this Failed to compile error.

![image](https://user-images.githubusercontent.com/22645740/132230397-81a0634f-7f8e-482f-b4bf-18fd3255e66f.png)

 It's trying to find ./assets.js but there is none in the project.

**Comment by codenamejason** [comment]
run yarn upload or remove the dependency for assets.js @Jharmony
