### ISSUE TITLE
creator has to manually re-set sale price after every sale

### ISSUE THREAD

**Issue by lucascerro** [austintgriffith/scaffold-eth#48]
The artist has to manually set a sale price for his artwork. After every sale, he has to re-set this price. Currently this is stopping people from actively exchanging xDai and NFTs due to lack of defined prices and easy buy button

Options:

- require user to set a price before "saving" his artwork
- offer opt-in (checkbox) to set the above price as fixed for all mintings [of one particular artwork]
- remind user he has to set a price in order for artwork to be sellable [if he has artwork with unset prices; dismissable]

**Comment by azf20** [comment]
Hey! You should be able to set a price to mint new artworks?
![image](https://user-images.githubusercontent.com/9612972/92302644-af4cc200-ef65-11ea-9b96-8c6b53e59f5e.png)
This shouldn't be re-set when someone buys a newly minted copy - we only re-set the price on the sale of individual NFTs (as presumably the buyer doesn't necessarily want to sell right away)
Let me know if that isn't working for you
We can definitely improve the UX though to prompt the artist to set the price - either in the original form as you say, or afterwards

**Comment by lucascerro** [comment]
This feedback originally came after seeing a colleague have re-set the sale price. I didn't understand what fully happened. But after going through the process myself I think it's pretty clear. Agree that maybe giving an option (checkbox) to set a sale price when sending original form might make it clearer that just sending artwork does not make it for sale. Or afterwards, just making it more obvious that "no sale price has been set; artwork is not on sale".

This is just ideas/speculation, though. Feel free to just close the issue. And nifty is awesome!

**Comment by azf20** [comment]
thanks - we are going to be spending some more time on nifty so may make some updates as you suggest! 👍
