### ISSUE TITLE
extra minting?

### ISSUE THREAD

**Issue by lucascerro** [austintgriffith/scaffold-eth#53]
So I'm not really sure what happened?

1) I made an artwork and shipped it

2) I bought the artwork (didn't know I would get one free)

3) I made another artwork and shipped it

4) now I have 3 copies of the first artwork?
https://blockscout.com/poa/xdai/address/0x9583648c314CDF666F4F555299dB3B36f5d5b2f9/transactions

I could swear I only made one purchase...

**Comment by codenamejason** [comment]
Going to close this for now.
