### ISSUE TITLE
Installing openzeppelin contracts 

### ISSUE THREAD

**Issue by akerbabber** [austintgriffith/scaffold-eth#59]
Hello, i would like to add openzeppelin contracts to my scaffold-eth project but i keep getting this error when running "yarn deploy".

Error BDLR403: Library openzeppelin-solidity is not installed.

I have installed it via "yarn add @openzeppelin/contracts", in various folder location, and also i tried to put directly openzeppelin contract into the buidler/contracts folder editing the import statement into my .sol files.

**Comment by codenamejason** [comment]
import "@openzeppelin/contracts/token/ERC20/ERC20.sol"; use like this.

**Comment by akerbabber** [comment]
It keeps giving me the same error, I want to run a gnosis conditional token (https://github.com/gnosis/conditional-tokens-contracts/tree/master/contracts) in scaffold and it requires openzeppelin IERC20.sol library.

Changing IERC20 CTHelpers.sol and ConditionalTokens.sol import statements to:
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
Gives the same error on `$yarn deploy:`

```
  yarn run v1.22.5
$ yarn workspace @scaffold-eth/buidler deploy
$ buidler run scripts/deploy.js && buidler run scripts/publish.js
Error BDLR403: Library openzeppelin-solidity is not installed.

For more info go to https://buidler.dev/BDLR403 or run Buidler with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js deploy
Directory: /home/akerbabber/Documents/tokentry2/condition
```

**Comment by akerbabber** [comment]
I have resolved the precedent step by using `yarn add '@gnosis.pm/conditional-tokens-contracts'`
Now when i try to compile all the imported contracts i can't compile different solidity versions:
`ParserError: Source file requires different compiler version (current compiler is 0.6.6+commit.6c089d02.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version`
How can I compile those files with the right solc compiler?
