### ISSUE TITLE
Failure on "yarn install" TypeError: patterns.map is not a function

### ISSUE THREAD

**Issue by iFirebrand** [austintgriffith/scaffold-eth#6]
Command line:

`yarn install v1.3.2
(node:25978) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error An unexpected error occurred: "patterns.map is not a function".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ifirebrand/devoffcloud/scaffold/rad-new-dapp/yarn-error.log".`

And yarn-error.log:

Trace: 
```
  TypeError: patterns.map is not a function
      at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:54024:78
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:92:30)
      at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:110:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:29389:28)
      at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:89:12
      at Config.resolveWorkspaces (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:54060:7)
      at /usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:21998:49
      at Generator.next (<anonymous>)
```

**Comment by corbinpage** [comment]
I got the same error.

**Comment by iFirebrand** [comment]
Resolution is a non-intuitive upgrade / downgrade:

1. brew install yarn
2. brew upgrade yarn

This upgrades to 1.22.4 from 1.3.2 🤷‍♂️
