### ISSUE TITLE
Buidler -> Hardhat?

### ISSUE THREAD

**Issue by jamespfarrell** [austintgriffith/scaffold-eth#66]
[Builder has become hardhat?](https://medium.com/nomic-labs-blog/buidler-has-evolved-introducing-hardhat-4bccd13bc931)

Wondering if I should wait for scaffold-eth to upgrade, if that's going to happen?

**Comment by jamespfarrell** [comment]
Austin told me on twitter, that it will upgraded at some point.

**Comment by aspiers** [comment]
I guess this can be upgraded now that #68 is merged?

**Comment by azf20** [comment]
Yep :)
