### ISSUE TITLE
Polls like crazy and locks up - Also lots of issues related to useEffect in Account.js

### ISSUE THREAD

**Issue by jeffscottward** [austintgriffith/scaffold-eth#7]
I would try VSCode as your editor and look in the console, I haven't been unable to untangle it yet.

**Comment by austintgriffith** [comment]
Make sure you have everything up (three different terminals):
```yarn start```
```yarn run chain```
```yarn run deploy```
All need to run or the app won't have what it needs and keeps looking :)

**Comment by jeffscottward** [comment]
Kk. Will try again this week.
Maybe write a bash script to spin up processes so you can tuck all those processes under one command.

**Comment by austintgriffith** [comment]
yeah I thought about that. Might make yarn start be one big script that brings everything up!

**Comment by codenamejason** [comment]
I think the point of having people run all three commands is to get the mental model down, then the user can modify if they choose.
