### ISSUE TITLE
clarify intended location of all React hooks for Ethereum 

### ISSUE THREAD

**Issue by aspiers** [austintgriffith/scaffold-eth#71]
Hi!

Just wondering if it was intentional to [reintroduce](https://github.com/austintgriffith/scaffold-eth/commit/5a3e07913f758e5b10defc8b77577ce355b40f95#diff-409938ab8e377a7fc51f22210de636b4f378cfe44e8536b0caf8b9de1a97ae43) the likes of [`src/hooks/Poller.js`](https://github.com/austintgriffith/scaffold-eth/blob/master/packages/react-app/src/hooks/Poller.js) and [`src/hooks/Balance.js`](https://github.com/austintgriffith/scaffold-eth/blob/master/packages/react-app/src/hooks/Balance.js) after 7168a289d73 deleted them in favour of [`eth-hooks`](https://github.com/austintgriffith/eth-hooks)?

If so, I'm curious of the reasoning.  I noticed because in some cases they are causing eslint warnings via the `react-hooks/exhaustive-deps` rule, which generally indicates a genuine bug.  I've submitted #70 to get a clean bill of health with eslint, but [there's still one unresolved warning in the `usePoller` hook due to a missing dependency on `fn`](https://github.com/austintgriffith/scaffold-eth/pull/70#issuecomment-727628897) and I'm not sure whether that needs to be fixed in this repo, or [in `eth-hooks`](https://github.com/austintgriffith/eth-hooks/blob/master/src/Poller.ts#L28), or both.

I also noticed that [the README claims they live in `packages/react-app/src`](https://github.com/austintgriffith/scaffold-eth#-hooks), which is currently true, but if the intention is to keep them in `eth-hooks` (as alluded to elsewhere in the same README) to avoid duplication then this should be updated for consistency too.  

Thanks!

**Comment by codenamejason** [comment]
We are working on a hooks solution now.
