### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by 0xTimepunk** [austintgriffith/scaffold-eth#72]
Hey!

Nice work with this! Any plans for upgrading to React 17?

Thanks

**Comment by pabloruiz55** [comment]
In theory React 17 doesn't bring new features and breaking changes are minimal if any.
https://es.reactjs.org/blog/2020/08/10/react-v17-rc.html

I think it should be very safe to give this upgrade a try.

**Comment by ShravanSunder** [comment]
CRA v4 is compatible with react 17.  https://github.com/facebook/create-react-app/releases/tag/v4.0.0

**Comment by ShravanSunder** [comment]
See PR https://github.com/austintgriffith/scaffold-eth/pull/278

**Comment by azf20** [comment]
This is done in https://github.com/austintgriffith/scaffold-eth/pull/278, nice @ShravanSunder !
