### ISSUE TITLE
remove node-gyp?

### ISSUE THREAD

**Issue by aspiers** [austintgriffith/scaffold-eth#73]
According to https://medium.com/nomic-labs-blog/turning-a-page-in-ethereum-javascript-history-4ec89136fccc there is no need to use `node-gyp` any more.  Given this and the fact that `scaffold-eth`'s `README` says `you might get node-gyp errors, ignore them`, can we follow the advice in that article?

**Comment by azf20** [comment]
hi! I think @austintgriffith already upgraded in line with that article's recommendations (so it's just the README that needs updating)

**Comment by aspiers** [comment]
Ah thanks, my branch was out of date so I missed this!  Leaving open as a reminder to fix the README.

**Comment by azf20** [comment]
Removed the warning in the README, thanks!
