### ISSUE TITLE
[BUG] Dollar ETH conversions don't match

### ISSUE THREAD

**Issue by ericelliott** [austintgriffith/scaffold-eth#8]
$191 faucet value becomes $1.91 in the wallet dollar conversion.

![Screen Shot 2020-05-15 at 2 20 52 PM](https://user-images.githubusercontent.com/364727/82097608-147b5f80-96b8-11ea-8a56-c28d827eb77a.png)

This seems so obvious that maybe it's intentional, but maybe there should be a corresponding checklist item to fix it?

**Comment by austintgriffith** [comment]
It must have sent twice I think. (You can send yourself as much as you want.)
If you click the $3.83 I bet it turns into 0.02

It would be cool to have a local block explorer come up with the stack so you could refer to it to double check stuff like this.

**Comment by ericelliott** [comment]
The issue is not that it sent twice, it's that it's 2 orders of magnitude off. The pill next to the faucet says $191.34, but only sends $1.91 according to the wallet balance display.

**Comment by easonchai** [comment]
@ericelliott Each time you send to the wallet, it only sends 0.01 ETH

**Comment by ericelliott** [comment]
I was confused because I didn't know what the number next to the faucet send was supposed to represent.
