### ISSUE TITLE
Error: Incompatible EIP155-based V 2710 and chain id 31337.

### ISSUE THREAD

**Issue by ironaddicteddog** [austintgriffith/scaffold-eth#81]
## Error message
The following error emerges when trying to send a transaction to local network:

```
MetaMask - RPC Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"Incompatible EIP155-based V 2710 and chain id 31337. See the second parameter of the Transaction constructor to set the chain id."}}}' 
```

## Environment
- `scaffold-eth`: commit [fdaab9f
](https://github.com/austintgriffith/scaffold-eth/commit/fdaab9f637697f119b1bfe7581e1450d8ca84509)
- `Node`: `v15.4.0`
- `Metamask`: `v8.1.8`

## Steps to reproduce
1. Follow the [quickstart](https://github.com/austintgriffith/scaffold-eth#quickstart) to run a fresh new `scaffold-eth`
2. Go to `http://localhost:3000`
3. Switch to metamask default `Localhost 8545` network
4. Input some text in `setPurpose` input field and click `Send`. Make sure the sender account has enough balance.

## Why does this happen?
This is due to the inconsistent of `chainId` from the metamask `Localhost 8545` (default `1337`) and hardhat network (default `31337`).

## How to fix this
To fix this, **you can either config the `chainId` of metamask `Localhost 8545` network or hardhat network**

### Config Metamask `Localhost 8545`
1. Open metamask and go to `setting` > `networks`
2. Locate network `Localhost 8545`
3. Change the `chainId` to the desired value, for example, `31337`

### Config hardhat
In `hardhat.config.js`:

1. Add a network `hardhat` in `hardhat.config.js` since `hardhat` is the default network used by hardhat network.
2. Add `chainId` in both `localhost` and `hardhat` section and config to the desired value:

```
...
  networks: {
    hardhat: {
      chainId: 1337
    },
    localhost: {
      url: "http://localhost:8545",
      chainId: 1337
    },
...
```

**Comment by sabotagebeats** [comment]
thanks this was helpful
