### ISSUE TITLE
"yarn graph-run-node" container failing to start on Apple M1

### ISSUE THREAD

**Issue by joaoritter** [austintgriffith/scaffold-eth#84]
Following Austin's tutorial at https://www.youtube.com/watch?v=T5ylzOTkn-Q&t=77s.

At minute 7:06 (running `yarn graph-run-node`) I'm running into a problem where the graph-node_1 container isn't starting up successfully.

![image](https://user-images.githubusercontent.com/5597861/103307730-cb75e280-49de-11eb-94e5-212401bed1ea.png)

I'm running the Apple M1 Tech Preview of Docker, maybe that has something to do with it. Check the "Known issues" of here: https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by joaoritter** [comment]
Confirmed that this is a Docker issue on Apple M1. The tutorial is working fine on my other computer.

**Comment by mohamadnabikhani** [comment]
got this error in Ubuntu v20.04!

**Comment by stevennevins** [comment]
Also having this issue on M1 :(

**Comment by stevennevins** [comment]
@joaoritter Try running yarn chain --hostname 0.0.0.0

**Comment by zy0n** [comment]
Not being on node 12 is the issue. 
nvm install 12 && nvm use 12
had this problem up until finding out I'm a fool, hovering over the node link in the readme, revealed version 12 in the url :P 
solved it for me.
loading blocks no issues now

also not sure if kubernetes and virtual frameworks needed

**Comment by pabloruiz55** [comment]
Has anyone had issues with Apple M1 recently? If not we'll close this issue soon.

**Comment by stevennevins** [comment]
No issues for me

**Comment by mejango** [comment]
None for me. Got it working a few weeks back.

**Comment by pabloruiz55** [comment]
Cool! Closing this issue then!
