### ISSUE TITLE
Expected identifier, got 'LParen'solc

### ISSUE THREAD

**Issue by thoms994** [austintgriffith/scaffold-eth#85]
Hi I'm currently editing my SmartContract.sol from the scaffold-eth project. 

By editing, I get the error "**Expected identifier, got 'LParen'solc**"

I think it is a noob question, but I'm grateful for every help I get. 

![image](https://user-images.githubusercontent.com/67169135/103458779-aac5c980-4d0b-11eb-84ef-3b7417a0279d.png)

**Comment by codenamejason** [comment]
I would just ignore that. Same thing happens to me, I think it is a VS Code thing with the linter.
